// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF9YsfaUteE0_4l-VN8M8q_VGIA_d1k2w',
    appId: '1:1031135608534:web:811d3c3b7c59cff3c51377',
    messagingSenderId: '1031135608534',
    projectId: 'sthenos-gym-ce563',
    authDomain: 'sthenos-gym-ce563.firebaseapp.com',
    storageBucket: 'sthenos-gym-ce563.firebasestorage.app',
    measurementId: 'G-5K0RX1RYFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2LNcmHXYjsD_MSJRSwbrK0h6XLgb_-I',
    appId: '1:1031135608534:android:efc84de6b561c509c51377',
    messagingSenderId: '1031135608534',
    projectId: 'sthenos-gym-ce563',
    storageBucket: 'sthenos-gym-ce563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTz3KN9qmN5P2BsUWDazjsmESqKE3PThs',
    appId: '1:1031135608534:ios:bb26287c6bd7272ec51377',
    messagingSenderId: '1031135608534',
    projectId: 'sthenos-gym-ce563',
    storageBucket: 'sthenos-gym-ce563.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
